### PR TITLE
Add VsCode Editor

### PR DESCRIPTION
**Pull request by ka1bi4**
Hi, @bodiam !
I added VsCode Editor and AsciiDoc extension.
It's very useful for work with asciidoc, pandoc and so on.

### CODE REVIEW

**Comment by bodiam** [comment]
Hi @ka1bi4 , thanks, I've added it!

**Comment by ka1bi4** [comment]
I modified the link to "Neo4j writing guide", it was broken.

**Comment by bodiam** [comment]
Hi @ka1bi4 , I didn't see your change for that, but I've changed it, and it's now pointing to https://github.com/neo4j-contrib/developer-resources. Thanks for letting me know!

**Comment by ka1bi4** [comment]
Oops, I didn't commit it. You've already fixed it.

I suggest adding some links about API documentation and AsciiDoc.

**Pull request merged**
